import base64
import os
import json
from io import BytesIO
from pathlib import Path

from PIL import Image

from tools.openai_client import client


GROCERY_PROFILE_PATH = Path(os.getenv("PAAI_DATA_DIR", "data")) / "grocery_profile.md"


def load_grocery_profile():
    if GROCERY_PROFILE_PATH.exists():
        return GROCERY_PROFILE_PATH.read_text(encoding="utf-8")

    return """
Default grocery profile:
- Do not assume common groceries unless visible.
- If image is unclear, mark manual check.
- Create a shopping list only from visible items, low-stock items, or listed household preferences.
"""


def image_to_base64(uploaded_file):
    image = Image.open(uploaded_file).convert("RGB")
    buffer = BytesIO()
    image.save(buffer, format="PNG")
    return base64.b64encode(buffer.getvalue()).decode("utf-8")


def create_shopping_message(grocery_json):
    shopping_items = grocery_json.get("shopping_list", [])

    if not shopping_items:
        return "No shopping list items found."

    lines = ["Grocery Shopping List:", ""]

    for item in shopping_items:
        name = item.get("item", "Unknown item")
        quantity = item.get("suggested_quantity", "")
        search_term = item.get("search_term", "")

        if quantity:
            lines.append(f"- {name}: {quantity}")
        else:
            lines.append(f"- {name}")

        if search_term:
            lines.append(f"  Search: {search_term}")

    lines.append("")
    lines.append("Generated by PAAI Grocery Photo Agent")

    return "\n".join(lines)


def extract_grocery_items_from_photo(uploaded_file):
    grocery_profile = load_grocery_profile()
    base64_image = image_to_base64(uploaded_file)

    prompt = f"""
You are the Grocery Photo Agent for PAAI.

Analyze the uploaded grocery, fridge, pantry, receipt, or shopping photo.

Use this household grocery profile:

{grocery_profile}

Return JSON only.

JSON format:
{{
  "visible_items": [
    {{
      "item": "string",
      "estimated_quantity": "string",
      "category": "Produce / Dairy / Pantry / Frozen / Beverage / Household / Other",
      "confidence": "High | Medium | Low",
      "notes": "string"
    }}
  ],
  "running_low": [
    {{
      "item": "string",
      "reason": "string",
      "confidence": "High | Medium | Low"
    }}
  ],
  "shopping_list": [
    {{
      "item": "string",
      "suggested_quantity": "string",
      "search_term": "string",
      "preferred_store": "Costco / Trader Joe's / Walmart / Indian grocery store / Any",
      "reason": "string",
      "confidence": "High | Medium | Low"
    }}
  ],
  "manual_check": [
    {{
      "item": "string",
      "reason": "string"
    }}
  ],
  "photo_quality": {{
    "score": 0,
    "suggestion": "How the user can upload a better photo"
  }},
  "summary": "string"
}}

Rules:
- Do not invent hidden items.
- Do not automatically add milk or eggs unless visible, listed in the profile, or clearly low.
- Do not claim exact measurement from the image.
- If unsure, use Low confidence.
- If the image is unclear, use manual_check instead of guessing.
- If expiry date is visible, add it to manual_check.
- Return valid JSON only.
- Do not include markdown.
"""

    response = client.responses.create(
        model="gpt-4.1-mini",
        input=[
            {
                "role": "user",
                "content": [
                    {"type": "input_text", "text": prompt},
                    {
                        "type": "input_image",
                        "image_url": f"data:image/png;base64,{base64_image}",
                    },
                ],
            }
        ],
    )

    raw_text = response.output_text

    try:
        grocery_json = json.loads(raw_text)
    except json.JSONDecodeError:
        grocery_json = {
            "visible_items": [],
            "running_low": [],
            "shopping_list": [],
            "manual_check": [
                {
                    "item": "Image or response",
                    "reason": "The model did not return valid JSON. Review manually.",
                }
            ],
            "photo_quality": {
                "score": 0,
                "suggestion": "Upload a clearer photo with items closer to the camera.",
            },
            "summary": "Could not parse grocery photo response.",
            "raw_output": raw_text,
        }

    grocery_json["shopping_message"] = create_shopping_message(grocery_json)

    return grocery_json


def save_grocery_analysis(result):
    from datetime import datetime
    from pathlib import Path
    import json
    import pandas as pd

    data_dir = Path("data")
    data_dir.mkdir(exist_ok=True)

    now = datetime.now().isoformat(timespec="seconds")

    latest_path = data_dir / "grocery_latest_result.json"
    history_path = data_dir / "grocery_upload_history.csv"

    result_to_save = dict(result)
    result_to_save["analyzed_at"] = now

    latest_path.write_text(
        json.dumps(result_to_save, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    history_row = {
        "analyzed_at": now,
        "summary": result.get("summary", ""),
        "shopping_items_count": len(result.get("shopping_list", [])),
        "visible_items_count": len(result.get("visible_items", [])),
        "manual_check_count": len(result.get("manual_check", [])),
        "photo_score": result.get("photo_quality", {}).get("score", ""),
    }

    if history_path.exists():
        history_df = pd.read_csv(history_path)
        history_df = pd.concat([history_df, pd.DataFrame([history_row])], ignore_index=True)
    else:
        history_df = pd.DataFrame([history_row])

    history_df.to_csv(history_path, index=False)

    return result_to_save


def load_grocery_history_info():
    from pathlib import Path
    import json
    import pandas as pd

    latest_path = Path(os.getenv("PAAI_DATA_DIR", "data")) / "grocery_latest_result.json"
    history_path = Path(os.getenv("PAAI_DATA_DIR", "data")) / "grocery_upload_history.csv"

    if not latest_path.exists() or not history_path.exists():
        return {
            "has_history": False,
            "message": "No previous grocery photo analysis found.",
        }

    latest_result = json.loads(latest_path.read_text(encoding="utf-8"))
    history_df = pd.read_csv(history_path)

    first_uploaded_at = history_df["analyzed_at"].iloc[0]
    last_uploaded_at = history_df["analyzed_at"].iloc[-1]

    return {
        "has_history": True,
        "first_uploaded_at": first_uploaded_at,
        "last_uploaded_at": last_uploaded_at,
        "latest_result": latest_result,
        "history_df": history_df,
    }


def is_grocery_analysis_stale(last_uploaded_at, stale_after_days=3):
    from datetime import datetime

    try:
        last_time = datetime.fromisoformat(str(last_uploaded_at))
        age_days = (datetime.now() - last_time).days
        return age_days >= stale_after_days, age_days
    except Exception:
        return True, None
